import React, { useState } from "react";
import {
  Scale,
  CheckCircle2,
  ShieldAlert,
  HelpCircle,
  Clock,
  AlertTriangle,
  ArrowRight,
  FileText,
  ExternalLink,
  ChevronRight,
  Gavel
} from "lucide-react";
import { CaseData } from "../types";
import { Language, Theme, translations } from "../lib/i18n";

interface CourtroomProps {
  caseData: CaseData;
  onSelectCitation: (citationId: string) => void;
  onOpenExportModal: () => void;
  lang: Language;
  theme: Theme;
}

export const Courtroom: React.FC<CourtroomProps> = ({
  caseData,
  onSelectCitation,
  onOpenExportModal,
  lang,
  theme,
}) => {
  const { courtroom } = caseData;
  const [activeTab, setActiveTab] = useState<"prosecution" | "defense" | "citations">("prosecution");
  const t = translations[lang];
  const runtime = caseData.runtime;
  const canExport = caseData.status === "court_ready" && courtroom.citedEvidence.length > 0;
  const runtimeLabel = runtime?.available
    ? `${runtime.gpuModel || "GPU"} · ${runtime.rocmVersion || "ROCm unknown"}`
    : "Local runtime unavailable";

  // Render citation tag button
  const renderCitationText = (text: string) => {
    // Citation IDs are generated by the local retriever and must remain
    // clickable even when the judge changes the surrounding prose.
    const parts = text.split(/(\[E-\d+\])/gi);
    return parts.map((part, i) => {
      const citationMatch = part.match(/^\[(E-\d+)\]$/i);
      if (citationMatch) {
        const citationId = citationMatch[1].toUpperCase();
        return (
          <button
            key={i}
            onClick={() => onSelectCitation(citationId)}
            className="inline-flex items-center gap-1 bg-cyan-950/80 hover:bg-cyan-800 text-cyan-300 border border-cyan-700/80 px-1.5 py-0.2 rounded font-mono text-[11px] font-bold mx-1 transition-colors hover:underline"
            title={`Jump to Evidence ${part}`}
          >
            {part}
            <ExternalLink className="w-2.5 h-2.5" />
          </button>
        );
      }
      return <span key={i}>{part}</span>;
    });
  };

  return (
    <div className={`flex-1 p-6 overflow-y-auto space-y-6 select-none transition-colors ${
      theme === 'dark' ? "bg-[#11141c] text-gray-200" : "bg-gray-100 text-gray-900"
    }`}>

      {/* Top Workflow Roles Pipeline */}
      <div className={`border rounded-lg p-4 font-mono text-xs ${
        theme === 'dark' ? "bg-[#181c26] border-gray-800" : "bg-white border-gray-300 shadow-sm"
      }`}>
        <div className="text-[10px] text-gray-500 font-bold uppercase tracking-widest mb-3 flex items-center justify-between">
          <span>TRI-ROLE ADVERSARIAL REASONING PIPELINE</span>
          <span className={`font-bold ${runtime?.available ? "text-emerald-500" : "text-amber-400"}`}>{runtimeLabel}</span>
        </div>
        <div className="flex items-center justify-between gap-3 text-center flex-wrap">
          <div className={`flex-1 p-3 rounded border font-bold flex items-center justify-center gap-2 ${
            theme === 'dark' ? "bg-[#121824] border-emerald-500/40 text-emerald-400" : "bg-emerald-50 border-emerald-300 text-emerald-800"
          }`}>
            <span>PROSECUTION</span>
            <CheckCircle2 className="w-4 h-4 text-emerald-500" />
          </div>

          <ArrowRight className="w-4 h-4 text-gray-400 shrink-0" />

          <div className={`flex-1 p-3 rounded border font-bold flex items-center justify-center gap-2 ${
            theme === 'dark' ? "bg-[#121824] border-cyan-500/40 text-cyan-400" : "bg-cyan-50 border-cyan-300 text-cyan-800"
          }`}>
            <span>DEFENSE</span>
            <CheckCircle2 className="w-4 h-4 text-cyan-500" />
          </div>

          <ArrowRight className="w-4 h-4 text-gray-400 shrink-0" />

          <div className={`flex-1 p-3 rounded border font-bold flex items-center justify-center gap-2 ${
            theme === 'dark' ? "bg-[#121824] border-amber-500/50 text-amber-400" : "bg-amber-50 border-amber-300 text-amber-800"
          }`}>
            <span>JUDGE</span>
            <CheckCircle2 className="w-4 h-4 text-amber-500" />
          </div>
        </div>
      </div>

      {/* Main Verdict Card */}
      <div className={`border-2 border-amber-500/40 rounded-lg p-6 space-y-4 shadow-2xl relative overflow-hidden ${
        theme === 'dark' ? "bg-[#181d28] text-gray-200" : "bg-amber-50/40 border-amber-400 text-gray-900"
      }`}>
        <div className="absolute top-0 right-0 bg-amber-500 text-gray-950 font-mono font-black text-[10px] px-3 py-1 rounded-bl uppercase">
          JUDICIAL VERDICT
        </div>

        <div className="flex items-center gap-3">
          <Gavel className="w-8 h-8 text-amber-500 shrink-0" />
          <div>
            <div className={`inline-block border px-2.5 py-0.5 rounded font-mono font-bold text-xs mb-1 ${
              theme === 'dark' ? "bg-amber-950 text-amber-400 border-amber-700/80" : "bg-amber-100 text-amber-900 border-amber-300"
            }`}>
              {courtroom.verdictStatus}
            </div>
            <h1 className={`text-xl font-bold font-sans ${
              theme === 'dark' ? "text-gray-100" : "text-gray-900"
            }`}>
              {courtroom.verdictTitle}
            </h1>
          </div>
        </div>

          <div className={`text-sm font-sans leading-relaxed border-t pt-3 ${
            theme === 'dark' ? "border-gray-800 text-gray-300" : "border-amber-200 text-gray-800"
          }`}>
            {courtroom.verdictSubtitle}
          </div>
          {caseData.error && (
            <div className="border border-amber-700/60 bg-amber-950/30 text-amber-200 rounded p-3 text-xs font-mono">
              LOCAL PIPELINE STATUS: {caseData.error}
            </div>
          )}

        <div className={`flex items-center justify-between text-xs font-mono pt-2 border-t flex-wrap gap-2 ${
          theme === 'dark' ? "border-gray-800 text-gray-400" : "border-amber-200 text-gray-600"
        }`}>
          <span>Confidence Score: <strong className="text-amber-500">{courtroom.confidence}%</strong></span>
          <span>Cited Evidence: <strong className="text-cyan-500">{courtroom.citedEvidence.join(", ")}</strong></span>
          <button
            onClick={onOpenExportModal}
            disabled={!canExport}
            className="bg-amber-500 hover:bg-amber-400 text-gray-950 font-bold px-3 py-1.5 rounded transition-colors text-xs disabled:opacity-40 disabled:cursor-not-allowed"
          >
            {t.exportBundle}
          </button>
        </div>
      </div>

      {/* Switchable Arguments Panels */}
      <div className={`border rounded-lg overflow-hidden ${
        theme === 'dark' ? "bg-[#181c26] border-gray-800" : "bg-white border-gray-300 shadow-sm"
      }`}>

        {/* Tab Headers */}
        <div className={`flex border-b font-mono text-xs ${
          theme === 'dark' ? "border-gray-800 bg-[#12151e]" : "border-gray-200 bg-gray-50"
        }`}>
          <button
            onClick={() => setActiveTab("prosecution")}
            className={`flex-1 py-3 px-4 font-bold transition-all border-b-2 text-center ${
              activeTab === "prosecution"
                ? theme === 'dark'
                  ? "border-emerald-500 text-emerald-400 bg-[#181c26]"
                  : "border-emerald-600 text-emerald-700 bg-white"
                : "border-transparent text-gray-400 hover:text-gray-200"
            }`}
          >
            PROSECUTION ARGUMENTS ({courtroom.prosecution.length})
          </button>
          <button
            onClick={() => setActiveTab("defense")}
            className={`flex-1 py-3 px-4 font-bold transition-all border-b-2 text-center ${
              activeTab === "defense"
                ? theme === 'dark'
                  ? "border-cyan-500 text-cyan-400 bg-[#181c26]"
                  : "border-cyan-600 text-cyan-700 bg-white"
                : "border-transparent text-gray-400 hover:text-gray-200"
            }`}
          >
            DEFENSE COUNTER-ARGUMENTS ({courtroom.defense.length})
          </button>
          <button
            onClick={() => setActiveTab("citations")}
            className={`flex-1 py-3 px-4 font-bold transition-all border-b-2 text-center ${
              activeTab === "citations"
                ? theme === 'dark'
                  ? "border-amber-500 text-amber-400 bg-[#181c26]"
                  : "border-amber-600 text-amber-700 bg-white"
                : "border-transparent text-gray-400 hover:text-gray-200"
            }`}
          >
            CITED EVIDENCE SUMMARY ({courtroom.citedEvidence.length})
          </button>
        </div>

        {/* Tab Content */}
        <div className="p-5 font-sans text-xs space-y-3">
          {activeTab === "prosecution" && (
            <ul className="space-y-2.5">
              {courtroom.prosecution.map((arg, idx) => (
                <li key={idx} className={`flex items-start gap-2.5 p-3 rounded border leading-relaxed ${
                  theme === 'dark' ? "bg-[#12151f] border-gray-800 text-gray-200" : "bg-gray-50 border-gray-200 text-gray-800"
                }`}>
                  <span className="w-5 h-5 rounded-full bg-emerald-100 text-emerald-800 border border-emerald-300 flex items-center justify-center font-mono font-bold text-[10px] shrink-0 mt-0.5">
                    P{idx + 1}
                  </span>
                  <div>{renderCitationText(arg)}</div>
                </li>
              ))}
            </ul>
          )}

          {activeTab === "defense" && (
            <ul className="space-y-2.5">
              {courtroom.defense.map((arg, idx) => (
                <li key={idx} className={`flex items-start gap-2.5 p-3 rounded border leading-relaxed ${
                  theme === 'dark' ? "bg-[#12151f] border-gray-800 text-gray-200" : "bg-gray-50 border-gray-200 text-gray-800"
                }`}>
                  <span className="w-5 h-5 rounded-full bg-cyan-100 text-cyan-800 border border-cyan-300 flex items-center justify-center font-mono font-bold text-[10px] shrink-0 mt-0.5">
                    D{idx + 1}
                  </span>
                  <div>{renderCitationText(arg)}</div>
                </li>
              ))}
            </ul>
          )}

          {activeTab === "citations" && (
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 font-mono">
              {caseData.evidenceList.map((item) => (
                <div
                  key={item.id}
                  onClick={() => onSelectCitation(item.id)}
                  className={`p-3 rounded border cursor-pointer transition-all flex items-center justify-between ${
                    theme === 'dark'
                      ? "bg-[#12151f] border-gray-800 hover:border-cyan-500/50 text-gray-200"
                      : "bg-gray-50 border-gray-200 hover:border-cyan-500 text-gray-800"
                  }`}
                >
                  <div className="truncate">
                    <span className="text-cyan-500 font-bold font-mono">[{item.id}]</span>
                    <span className="font-sans ml-2 text-xs truncate">{item.filename}</span>
                  </div>
                  <ChevronRight className="w-4 h-4 text-gray-400" />
                </div>
              ))}
            </div>
          )}
        </div>

      </div>

      {/* Bottom Section */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4 font-mono text-xs">

        {/* Contradiction Timeline */}
        <div className={`border p-4 rounded-lg space-y-3 ${
          theme === 'dark' ? "bg-[#181c26] border-gray-800" : "bg-white border-gray-300 shadow-sm"
        }`}>
          <div className="text-xs font-bold text-gray-500 flex items-center gap-2 border-b pb-2">
            <Clock className="w-4 h-4 text-cyan-500" />
            {t.contradictionTimeline}
          </div>
          <div className="space-y-2 font-sans text-xs">
            {courtroom.timeline.map((item, idx) => (
              <div key={idx} className="border-l-2 border-cyan-500 pl-2.5 py-1 space-y-0.5">
                <div className="font-mono text-[10px] text-cyan-500 font-bold">{item.date}</div>
                <div className={theme === 'dark' ? "text-gray-200 text-xs" : "text-gray-800 text-xs"}>{item.event}</div>
              </div>
            ))}
          </div>
        </div>

        {/* Missing Evidence */}
        <div className={`border p-4 rounded-lg space-y-3 ${
          theme === 'dark' ? "bg-[#181c26] border-gray-800" : "bg-white border-gray-300 shadow-sm"
        }`}>
          <div className="text-xs font-bold text-gray-500 flex items-center gap-2 border-b pb-2">
            <AlertTriangle className="w-4 h-4 text-amber-500" />
            {t.missingEvidence}
          </div>
          <ul className="space-y-2 font-sans text-xs">
            {courtroom.missingEvidence.length > 0 ? (
              courtroom.missingEvidence.map((item, idx) => (
                <li key={idx} className={`p-2 rounded border flex items-start gap-2 ${
                  theme === 'dark' ? "bg-[#12151f] border-amber-900/40 text-amber-200" : "bg-amber-50 border-amber-200 text-amber-900"
                }`}>
                  <span className="text-amber-500 font-bold">•</span>
                  <span>{item}</span>
                </li>
              ))
            ) : (
              <div className="text-emerald-500 py-2">No crucial missing evidence identified.</div>
            )}
          </ul>
        </div>

        {/* Recommended Next Action */}
        <div className={`border p-4 rounded-lg space-y-3 ${
          theme === 'dark' ? "bg-[#181c26] border-gray-800" : "bg-white border-gray-300 shadow-sm"
        }`}>
          <div className="text-xs font-bold text-gray-500 flex items-center gap-2 border-b pb-2">
            <CheckCircle2 className="w-4 h-4 text-emerald-500" />
            {t.nextAction}
          </div>
          <div className={`border p-3 rounded font-sans text-xs leading-relaxed ${
            theme === 'dark' ? "bg-[#0f1715] border-emerald-800/60 text-emerald-300" : "bg-emerald-50 border-emerald-200 text-emerald-900"
          }`}>
            {courtroom.nextAction}
          </div>
        </div>

      </div>

    </div>
  );
};
